version: '3.8'

services:
  flash_cards_api_dev:
    container_name: flash_cards_api_dev
    image: flash_cards_api_dev:1.0.0
    build:
      context: .
      target: development
    ports:
      - ${PORT}:${PORT}
    depends_on: 
      - flash_cards_mongodb
    volumes:
      - ./:/usr/src/app
    command: npm run start:dev
    restart: unless-stopped

  flash_cards_mongodb:
    container_name: ${DATABASE_HOST}
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD} 
    expose:
      - ${DATABASE_PORT}
    volumes:
      - ./mongo-data:/data/db 
    restart: unless-stopped

networks:
  default:
    driver: bridge
